dtb-$(CONFIG_ARCH_MXC) += ucm-imx8m-mini.dtb
dtb-$(CONFIG_ARCH_MXC) += ucm-imx8m-mini-eb-dsi2lvds.dtb
dtb-$(CONFIG_ARCH_MXC) += ucm-imx8m-mini-m4.dts

always         := $(dtb-y)
subdir-y       := $(dts-dirs)
clean-files    := *.dtb
